### ISSUE TITLE
ITU/ISO identifier

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-itu#28]
The identifier `ITU-T Y.3500 (08/2014) | ISO/IEC 17788` is not a single identifier, but two identifiers:

````
<docidentifier type="ITU">ITU-T Y.3500</docidentifier>
<docidentifier type="ISO">ISO/IEC 17788</docidentifier>
````

Under ITU, we expect to cite this document only as ITU-T Y.3500.

**Comment by ronaldtse** [comment]
The method of encoding described by @opoudjis  is correct for Relaton.

However, the citation display for ITU is incorrect.

From ITU Editing Guidelines:

<img width="771" alt="Screen Shot 2019-10-20 at 5 03 33 PM" src="https://user-images.githubusercontent.com/11865/67157203-8d514d80-f35b-11e9-8067-41c5142c54d2.png">

Since ITU-T Y.3500 has two identifiers, it is considered to be case 2:

"Identical Recommendation | International Standard (or "common text")": both identifiers should be shown in the citation.

The rendering is done in Metanorma, so I will file the ticket there.
