### ISSUE TITLE
Unable to fetch ITU-T H.248.1

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#53]
```
[relaton-itu] ("ITU-T H.248.1") fetching...
[relaton-itu] WARNING: no match found online for ITU-T H.248.1:2013. The code must be exactly like it is on the standards website.
[relaton-itu] If you wanted to cite all document parts for the reference, use "ITU-T H.248.1 (all parts)".
If the document is not a standard, use its document type abbreviation (TS, TR, PAS, Guide).
[relaton-itu] ("ITU-T H.248.9") fetching...
[relaton-itu] ("ITU-T H.248.9") found ITU-T H.248.9
[relaton-itu] ("ITU-T H.248.40") fetching...
[relaton-itu] ("ITU-T H.248.40") found ITU-T H.248.40
```

The document exists though.

Using relaton-itu (1.7.3).

**Comment by andrew2net** [comment]
@ronaldtse the document `ITU-T H.248.1` has type "Meeting Document". There are only "Recommendations" with a version like `ITU-T H.248.1 v3`.
Currently, the relaton-itu filters search results by document type "Recommendation". Without this filter, we will get "Meeting documents" instead of "Recommendations" in some cases. 
Do we need to return "Recommendation" `ITU-T H.248.1 v3` or "Meeting Document" `ITU-T H.248.1` for reference `ITU-T H.248.1`?

**Comment by ronaldtse** [comment]
@andrew2net the document "ITU-T H.248.1" is a Recommendation:
https://www.itu.int/rec/T-REC-H.248.1

The version specifier is not part of the document identifier, so "ITU-T H.248.1" is correct

Where do you get that ITU-T H.248.1 is a Meeting Document?

**Comment by andrew2net** [comment]
@ronaldtse the [ITU search](https://www.itu.int/net4/ITU-T/search/GlobalSearch) didn't find the document 2 weeks ago. It does now. So the issue has gone.

**Comment by ronaldtse** [comment]
That's great, thanks!
